package com.quvideo.application.db;

import android.content.ContentValues;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import com.quvideo.application.draft.DraftModel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "xyt_info_v2".
 */
public class DraftInfoDao extends SuperAbstractDB<DraftModel> {

  public static final String TABLENAME = "draft_info";

  /**
   * Properties of entity XytInfo.<br/>
   * Can be used for QueryBuilder and for referencing column names.
   */
  public final static ItemProperty Id = new ItemProperty(0, Long.class, true, "id");
  public final static ItemProperty ProjectUrl = new ItemProperty(1, String.class, false, "projectUrl");
  public final static ItemProperty DraftCreateTime = new ItemProperty(2, Long.class, false, "createTime");

  public DraftInfoDao() {
    super();
  }

  @Override protected String getTableName() {
    return TABLENAME;
  }

  @Override public DraftModel cursorToItem(Cursor cursor) {
    DraftModel entity = new DraftModel();
    entity.id = cursor.isNull(Id.ordinal) ? null : cursor.getLong(Id.ordinal);
    entity.projectUrl = cursor.isNull(ProjectUrl.ordinal) ? null : cursor.getString(ProjectUrl.ordinal);
    entity.createTime = cursor.isNull(DraftCreateTime.ordinal) ? null : cursor.getLong(DraftCreateTime.ordinal);
    return entity;
  }

  @Override public ContentValues itemToContentValues(DraftModel entity) {
    ContentValues cv = new ContentValues();
    if (entity.id != 0) {
      cv.put(Id.columnName, entity.id);
    }
    cv.put(DraftCreateTime.columnName, entity.createTime);
    if (entity.projectUrl != null) {
      cv.put(ProjectUrl.columnName, entity.projectUrl);
    }
    return cv;
  }

  @Override public void removeItem(DraftModel paramT) {
    sdb.delete(TABLENAME, Id.columnName + "=?", new String[] { "" + paramT.getId() });
  }

  @Override public void updateItem(DraftModel paramT) {
    ContentValues cv = itemToContentValues(paramT);
    sdb.update(TABLENAME, cv, Id.columnName + "=?", new String[] { "" + paramT.getId() });
  }

  /** Drops the underlying database table. */
  public static void dropTable(SQLiteDatabase db) {
    String sql = "DROP TABLE IF EXISTS \"" + TABLENAME + "\"";
    db.execSQL(sql);
  }

  /** Creates the underlying database table. */
  public static void createTable(SQLiteDatabase db) {
    db.execSQL("CREATE TABLE IF NOT EXISTS \"" + TABLENAME + "\" (" + //
        "\"" + Id.columnName + "\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
        "\"" + ProjectUrl.columnName + "\" TEXT UNIQUE," + // 5: filePath
        "\"" + DraftCreateTime.columnName + "\" LONG NOT NULL );"); // 19: templateDefault
  }
}
